# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

In [4]:
import numpy as np

In [8]:
x = np.float32(1.0)
x

1.0

In [11]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [12]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [16]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [20]:
z.astype(float)

array([0., 1., 2.])

In [18]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [21]:
z.dtype

dtype('uint8')