# Regularização
- l1
- l2
- elasticnet

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
# https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
df_wine = pd.read_csv('wine.data', header=None)


df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

Class labels [1 2 3]


Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0            1    14.23        1.71  2.43               15.6        127   
1            1    13.20        1.78  2.14               11.2        100   
2            1    13.16        2.36  2.67               18.6        101   
3            1    14.37        1.95  2.50               16.8        113   
4            1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [3]:
X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.3, 
                     random_state=0, 
                     stratify=y)

In [4]:
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [8]:
model_none = linear_model.LogisticRegression(penalty='l1', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[-1.26336366 -1.21618634 -2.37024246]
coef_:
[[ 1.24570162  0.18080713  0.74353603 -1.16136393  0.          0.
   1.17018229  0.          0.          0.          0.          0.54694578
   2.5105225 ]
 [-1.53703752 -0.38783998 -0.99522581  0.36515494 -0.05971764  0.
   0.6679069   0.          0.         -1.93444244  1.23318828  0.
  -2.23120752]
 [ 0.13569598  0.16855897  0.35714641  0.          0.          0.
  -2.43805494  0.          0.          1.56356741 -0.81860375 -0.4927206
   0.        ]]


/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [9]:
model_none = linear_model.LogisticRegression(penalty='l1', C=1000, random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[ -5.34367555  -9.83597933 -10.34822926]
coef_:
[[  7.37971842   1.81843827   4.09097135  -5.93813415   0.67779717
    0.           5.14286923   0.           0.7666902   -1.60830282
   -1.53632016   3.05438695   8.05538403]
 [ -5.87746531  -2.99270879  -7.04717127   3.7063072   -0.54593881
    0.           4.74976612   2.88915393   0.         -18.86491688
    5.39725019   0.5877811  -16.25710372]
 [  4.11244662   0.79818694   4.04740036   0.          -0.27890452
    0.86776836  -8.616848    -2.09840888  -1.74589349   7.96442912
   -5.91091895  -3.93415426   0.69609926]]


/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [6]:
model_none = linear_model.LogisticRegression(penalty='l2', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[-1.33509136 -0.96973542 -2.04898785]
coef_:
[[ 1.27713853  0.38210274  0.8015599  -1.30842842  0.22782837  0.23101419
   0.90234371 -0.08423823  0.01462196 -0.0312838   0.02796323  0.71703048
   1.79262118]
 [-1.45395571 -0.620303   -1.05445248  0.67148394 -0.29048951  0.18277571
   0.51163918  0.10789643  0.08199321 -1.61228834  0.88800662  0.1659356
  -1.73246957]
 [ 0.38965148  0.4083047   0.40211468  0.26242969  0.15288658 -0.20064653
  -1.38792256 -0.06305419 -0.28440345  1.2553389  -0.93849662 -0.83821807
   0.13754706]]


/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [7]:
model_none = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg', penalty='l2', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[ 0.36862533  0.78036204 -1.14898737]
coef_:
[[ 0.78792639  0.24089338  0.4473384  -0.73489829  0.1113343   0.22607273
   0.60652205 -0.14847572  0.24131476  0.14140959  0.10670518  0.58061102
   0.98240089]
 [-0.95393153 -0.43668273 -0.76795841  0.50646632 -0.17622299  0.07110642
   0.38809799  0.09343743  0.11353057 -0.91231356  0.61090399  0.16780023
  -1.10002567]
 [ 0.16600514  0.19578935  0.32062001  0.22843197  0.06488869 -0.29717916
  -0.99462004  0.05503829 -0.35484533  0.77090397 -0.71760916 -0.74841125
   0.11762478]]


In [10]:
model_none = linear_model.SGDClassifier(loss='modified_huber', penalty='none', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:1.0
intercept_:
[-201.07631485 -116.83845336 -298.83174314]
coef_:
[[ 184.0837208     4.97847036  200.80760411 -244.769326    -37.28502688
    34.94173915  107.20826247   -5.3349541    33.32242095   -8.88345234
    39.39087707  104.58864457  175.57518504]
 [-181.46269972  -79.94220401 -178.19711545  111.00749513  -18.09383234
   -23.49236238   95.56119945   51.25561724  -38.65543097 -267.59709082
   177.60799045   57.10920891 -281.76635673]
 [  45.36899167   39.20740018   85.94673151    6.47688697    0.97451069
   -53.23989804 -192.78059131  -21.57630735  -56.30943776  182.53863486
  -104.18774991 -106.08480099   33.3915707 ]]


In [11]:
model_l1 = linear_model.SGDClassifier(loss='modified_huber', penalty='l1', random_state=0)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.9814814814814815
intercept_:
[-201.07631485 -116.83845336 -298.83174314]
coef_:
[[ 184.0837208     4.97847036  200.80760411 -244.769326    -37.28502688
    34.94173915  107.20826247   -5.3349541    33.32242095   -8.88345234
    39.39087707  104.58864457  175.57518504]
 [-181.46269972  -79.94220401 -178.19711545  111.00749513  -18.09383234
   -23.49236238   95.56119945   51.25561724  -38.65543097 -267.59709082
   177.60799045   57.10920891 -281.76635673]
 [  45.36899167   39.20740018   85.94673151    6.47688697    0.97451069
   -53.23989804 -192.78059131  -21.57630735  -56.30943776  182.53863486
  -104.18774991 -106.08480099   33.3915707 ]]


In [10]:
model_l2 = linear_model.SGDClassifier(loss='modified_huber', penalty='l2', random_state=0,)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.9814814814814815
intercept_:
[-201.07631485 -116.83845336 -298.83174314]
coef_:
[[ 184.0837208     4.97847036  200.80760411 -244.769326    -37.28502688
    34.94173915  107.20826247   -5.3349541    33.32242095   -8.88345234
    39.39087707  104.58864457  175.57518504]
 [-181.46269972  -79.94220401 -178.19711545  111.00749513  -18.09383234
   -23.49236238   95.56119945   51.25561724  -38.65543097 -267.59709082
   177.60799045   57.10920891 -281.76635673]
 [  45.36899167   39.20740018   85.94673151    6.47688697    0.97451069
   -53.23989804 -192.78059131  -21.57630735  -56.30943776  182.53863486
  -104.18774991 -106.08480099   33.3915707 ]]


In [11]:
model = linear_model.SGDClassifier(loss='modified_huber', penalty='elasticnet', random_state=0)
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:1.0
intercept_:
[-201.07631485 -116.83845336 -298.83174314]
coef_:
[[ 184.0837208     4.97847036  200.80760411 -244.769326    -37.28502688
    34.94173915  107.20826247   -5.3349541    33.32242095   -8.88345234
    39.39087707  104.58864457  175.57518504]
 [-181.46269972  -79.94220401 -178.19711545  111.00749513  -18.09383234
   -23.49236238   95.56119945   51.25561724  -38.65543097 -267.59709082
   177.60799045   57.10920891 -281.76635673]
 [  45.36899167   39.20740018   85.94673151    6.47688697    0.97451069
   -53.23989804 -192.78059131  -21.57630735  -56.30943776  182.53863486
  -104.18774991 -106.08480099   33.3915707 ]]


In [12]:
np.unique(y)

array([1, 2, 3])